name: detec
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.14=h993c535_1
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - certifi==2025.7.14
    - charset-normalizer==3.4.2
    - contourpy==1.3.2
    - cycler==0.12.1
    - fonttools==4.59.0
    - idna==3.10
    - kiwisolver==1.4.8
    - labelimg==1.8.6
    - lap==0.5.12
    - lxml==6.0.0
    - matplotlib==3.10.3
    - numpy==1.23.0
    - opencv-python==4.12.0.88
    - packaging==25.0
    - pandas==2.3.1
    - pillow==11.3.0
    - psutil==7.0.0
    - py-cpuinfo==9.0.0
    - pyparsing==3.2.3
    - pyproj==3.7.1
    - pyqt5==5.15.11
    - pyqt5-qt5==5.15.17
    - pyqt5-sip==12.17.0
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.2
    - requests==2.32.4
    - scipy==1.15.3
    - seaborn==0.13.2
    - setuptools==78.1.1
    - six==1.17.0
    - torch==1.12.1+cu113
    - torchaudio==0.12.1+cu113
    - torchvision==0.13.1+cu113
    - tqdm==4.67.1
    - typing-extensions==4.14.1
    - tzdata==2025.2
    - ultralytics==8.3.88
    - ultralytics-thop==2.0.14
    - urllib3==2.5.0
    - wheel==0.45.1
